version: '3.8'  # Ensure the version supports the platform setting

services:
  rag_ai:
    build:
      context: .
      # platform should be placed at the top level in Docker Compose v3.8 and above
    platform: linux/amd64
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1