version: '3.8'

services:
  rag_ai:
    build:
      context: .
    platform: linux/amd64
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1
